In [4]:
import tushare as ts
import pandas as pd

In [5]:
ts.set_token('f4ec414585a3b828b1eafe0f03a6fdb582c1ab257a6aca0164b99b2f')
pro = ts.pro_api()

okexFutureEth = pro.coinbar(exchange='future_okex', symbol='btcusdt', freq='60min', start_date='20190102', end_date='20190220',contract_type='quarter')

In [127]:
okexFutureEth#DataFrame

,symbol,date,open,high,low,close,vol
0,btcusdt,2019-02-20 00:00:00,3979.44,3997.04,3975.00,3975.98,8861.498790
1,btcusdt,2019-02-19 23:00:00,3961.96,3996.00,3960.00,3979.70,5307.196355
2,btcusdt,2019-02-19 22:00:00,3987.61,4004.00,3945.73,3961.50,12623.556427
3,btcusdt,2019-02-19 21:00:00,3930.88,4014.41,3926.00,3987.63,15418.622081
4,btcusdt,2019-02-19 20:00:00,3916.37,3935.00,3915.42,3931.00,3940.461966
5,btcusdt,2019-02-19 19:00:00,3911.58,3919.37,3904.00,3916.13,2238.857222
6,btcusdt,2019-02-19 18:00:00,3904.40,3912.92,3892.88,3911.98,4370.943596
7,btcusdt,2019-02-19 17:00:00,3925.08,3935.00,3896.66,3904.40,4923.859923
8,btcusdt,2019-02-19 16:00:00,3930.19,3938.49,3916.03,3925.03,3168.651782
9,btcusdt,2019-02-19 15:00:00,3917.67,3934.61,3916.27,3930.19,3930.570695
10,btcusdt,2019-02-19 14:00:00,3907.21,3922.72,3902.66,3917.67,2529.284931
11,btcusdt,2019-02-19 13:00:00,3920.03,3926.27,3893.00,3907.20,5367.733927
12,btcusdt,2019-02-19 12:00:00,3903.49,3928.77,3902.70,3919.60,4622.616837
13,btcusdt,2019-02-19 11:00:00,3898.14,3912.98,3896.25,3903.54,3964.686842
14,btcusdt,2019-02-19 10:00:00,3910.20,3920.40,3892.00,3898.08,5016.899357
15,btcusdt,2019-02-19 09:00:00,3968.79,3968.80,3890.00,3910.00,10435.802175
16,btcusdt,2019-02-19 08:00:00,3909.68,3993.00,3906.09,3968.80,15199.689737
17,btcusdt,2019-02-19 07:00:00,3902.31,3915.01,3892.48,3910.05,3536.414993
18,btcusdt,2019-02-19 06:00:00,3892.39,3902.31,3873.00,3902.31,2840.380360
19,btcusdt,2019-02-19 05:00:00,3905.26,3916.44,3890.70,3892.16,2173.382301
20,btcusdt,2019-02-19 04:00:00,3900.02,3909.52,3892.53,3905.26,7258.163137
21,btcusdt,2019-02-19 03:00:00,3911.11,3923.55,3900.00,3900.02,4000.262204
22,btcusdt,2019-02-19 02:00:00,3892.62,3923.85,3884.83,3911.71,5047.983066
23,btcusdt,2019-02-19 01:00:00,3901.06,3914.83,3871.28,3892.96,11504.768744
24,btcusdt,2019-02-19 00:00:00,3817.20,3949.00,3816.28,3901.19,35224.438529
25,btcusdt,2019-02-18 23:00:00,3806.34,3821.80,3791.00,3817.01,6331.090981
26,btcusdt,2019-02-18 22:00:00,3791.13,3839.82,3787.00,3806.29,15610.521080
27,btcusdt,2019-02-18 21:00:00,3740.12,3821.00,3719.97,3791.64,24430.875330
28,btcusdt,2019-02-18 20:00:00,3714.00,3750.00,3693.85,3740.10,9263.422619
29,btcusdt,2019-02-18 19:00:00,3693.79,3725.72,3692.99,3713.89,5040.335121
...,...,...,...,...,...,...,...
1147,btcusdt,2019-01-03 05:00:00,3738.44,3770.00,3721.52,3750.00,4589.927364
1148,btcusdt,2019-01-03 04:00:00,3715.71,3740.00,3707.69,3738.10,3340.076534
1149,btcusdt,2019-01-03 03:00:00,3714.98,3715.96,3688.69,3715.39,2943.420546
1150,btcusdt,2019-01-03 02:00:00,3717.32,3721.20,3697.95,3715.00,3027.751604
1151,btcusdt,2019-01-03 01:00:00,3712.87,3729.88,3703.00,3717.32,3825.219139
1152,btcusdt,2019-01-03 00:00:00,3689.99,3761.00,3683.64,3712.86,8220.811043
1153,btcusdt,2019-01-02 23:00:00,3700.04,3705.00,3677.00,3691.86,3927.363788
1154,btcusdt,2019-01-02 22:00:00,3718.00,3722.10,3688.00,3700.00,6064.397866
1155,btcusdt,2019-01-02 21:00:00,3686.14,3738.08,3679.71,3717.00,10561.723914
1156,btcusdt,2019-01-02 20:00:00,3679.40,3690.00,3666.67,3685.51,3623.518214
1157,btcusdt,2019-01-02 19:00:00,3681.00,3701.10,3662.71,3678.63,5277.488765
1158,btcusdt,2019-01-02 18:00:00,3669.74,3688.94,3664.46,3681.00,4119.182991
1159,btcusdt,2019-01-02 17:00:00,3676.38,3676.78,3662.71,3670.30,3443.535597
1160,btcusdt,2019-01-02 16:00:00,3669.90,3687.15,3668.20,3676.38,4971.020098
1161,btcusdt,2019-01-02 15:00:00,3654.41,3671.21,3649.43,3669.90,4551.830251
1162,btcusdt,2019-01-02 14:00:00,3673.75,3675.75,3638.00,3655.23,6257.024028
1163,btcusdt,2019-01-02 13:00:00,3677.41,3681.00,3671.00,3673.87,2576.938708
1164,btcusdt,2019-01-02 12:00:00,3673.00,3681.56,3666.58,3677.69,3173.398173
1165,btcusdt,2019-01-02 11:00:00,3678.51,3688.96,3670.02,3673.00,3561.795775
1166,btcusdt,2019-01-02 10:00:00,3672.32,3682.99,3663.00,3678.49,3832.925371
1167,btcusdt,2019-01-02 09:00:00,3679.30,3692.96,3667.00,3672.31,4281.289632
1168,btcusdt,2019-01-02 08:00:00,3699.62,3715.14,3662.71,3679.10,7353.418548
1169,btcusdt,2019-01-02 07:00:00,3607.18,3704.37,3605.00,3702.09,13631.377035
1170,btcusdt,2019-01-02 06:00:00,3608.48,3614.03,3592.87,3607.13,2462.292486
1171,btcusdt,2019-01-02 05:00:00,3618.26,3629.00,3605.60,3609.45,2566.709206
1172,btcusdt,2019-01-02 04:00:00,3593.48,3628.47,3588.02,3618.18,6480.874092
1173,btcusdt,2019-01-02 03:00:00,3545.00,3602.11,3543.57,3593.58,4036.237310
1174,btcusdt,2019-01-02 02:00:00,3576.85,3576.85,3505.99,3544.98,7113.779833
1175,btcusdt,2019-01-02 01:00:00,3579.78,3584.86,3563.00,3576.85,2652.741773
1176,btcusdt,2019-01-02 00:00:00,3571.20,3582.02,3566.98,3579.78,3120.419322

In [124]:
okexFutureEth.to_csv('/Users/davidli/Documents/btc-eth/perpetual.csv')

In [43]:
okexFutureEth['date']

0       2019-02-20 00:00:00
1       2019-02-19 23:00:00
2       2019-02-19 22:00:00
3       2019-02-19 21:00:00
4       2019-02-19 20:00:00
5       2019-02-19 19:00:00
6       2019-02-19 18:00:00
7       2019-02-19 17:00:00
8       2019-02-19 16:00:00
9       2019-02-19 15:00:00
10      2019-02-19 14:00:00
11      2019-02-19 13:00:00
12      2019-02-19 12:00:00
13      2019-02-19 11:00:00
14      2019-02-19 10:00:00
15      2019-02-19 09:00:00
16      2019-02-19 08:00:00
17      2019-02-19 07:00:00
18      2019-02-19 06:00:00
19      2019-02-19 05:00:00
20      2019-02-19 04:00:00
21      2019-02-19 03:00:00
22      2019-02-19 02:00:00
23      2019-02-19 01:00:00
24      2019-02-19 00:00:00
25      2019-02-18 23:00:00
26      2019-02-18 22:00:00
27      2019-02-18 21:00:00
28      2019-02-18 20:00:00
29      2019-02-18 19:00:00
               ...
1147    2019-01-03 05:00:00
1148    2019-01-03 04:00:00
1149    2019-01-03 03:00:00
1150    2019-01-03 02:00:00
1151    2019-01-03 01:00:00
1152    2019-01-03 00:00:00
1153    2019-01-02 23:00:00
1154    2019-01-02 22:00:00
1155    2019-01-02 21:00:00
1156    2019-01-02 20:00:00
1157    2019-01-02 19:00:00
1158    2019-01-02 18:00:00
1159    2019-01-02 17:00:00
1160    2019-01-02 16:00:00
1161    2019-01-02 15:00:00
1162    2019-01-02 14:00:00
1163    2019-01-02 13:00:00
1164    2019-01-02 12:00:00
1165    2019-01-02 11:00:00
1166    2019-01-02 10:00:00
1167    2019-01-02 09:00:00
1168    2019-01-02 08:00:00
1169    2019-01-02 07:00:00
1170    2019-01-02 06:00:00
1171    2019-01-02 05:00:00
1172    2019-01-02 04:00:00
1173    2019-01-02 03:00:00
1174    2019-01-02 02:00:00
1175    2019-01-02 01:00:00
1176    2019-01-02 00:00:00
Name: date, Length: 1177, dtype: object

In [106]:
time_list = okexFutureEth['date']
price_list_high = okexFutureEth['close']
volume_list = okexFutureEth['vol']

In [107]:
length = len(time_list)
coeff = (-1) * length
new_time_list = time_list[::-1]
new_price_list = price_list_high[::-1]
new_volume_list = volume_list[::-1]

In [2]:
datamix = np.array([new_price_list,new_volume_list]).T

NameError: name 'np' is not defined

In [134]:
data = pd.DataFrame(datamix,index = new_time_list,columns=['price', 'vol'])

In [1]:
datamix

NameError: name 'datamix' is not defined

In [140]:
data['return'] = data['price'].pct_change()

data

In [137]:
clean_data = np.array(data['return'].dropna())

In [138]:
clean_data

array([-0.00081849, -0.00891007,  0.01370953, ..., -0.00655276,
        0.00459422, -0.00093474])

In [139]:
clean_data.plt()

AttributeError: 'numpy.ndarray' object has no attribute 'plt'